image: ruby:2.7

cache:
  paths:
    - vendor/

before_script:
  - cd docs
  - gem install bundler
  - bundle install
  - cd ..

pages:
  script:
    - cd docs
    - bundle exec jekyll build -d ../public
    - cd ..
  artifacts:
    paths:
      - public
